### ISSUE TITLE
Request: Check for typical errors

### ISSUE THREAD

**Issue by bubeck** [openAIP/openaip-openair-parser#29]
I am willing to improve your parser and before doing this, I would like to get your feedback on the idea and if you would be willing to accept the changes:

**PROBLEM:**

This is an excerpt from german airspace which is very typical
````
DP 48:38:54 N 009:37:28 E
V D=-
V X=48:41:19 N 009:12:39 E
DB 48:38:54 N 009:37:25 E, 48:53:47 N 009:29:13 E
DP 48:49:10 N 008:47:51 E
````

the problem is the first coordinates of "DB". It is very close (18m) to the previous DP and I think this is a human mistake. The author always tried to have the same coordinates for:

 * The first coordinates of DB and the previous DP
 * the second coordinates of DB and the next DP

However, sometimes they differ by a few meters.

**IMPACT:**

You can see the resulting problem, if you zoom into the airspace as presented by http://airspace.xcontest.org or burnair.cloud or whatever. It is kind of "zick zack". I also work for a paragliding computer called "strato" (https://github.com/fhorinek/BB) implementing airspace calculation. They also suffer from this problem, as too many intersections are found, because of wrong coordinates.

**PROPOSED SOLUTION**

Either check explicitely for the above two cases in https://github.com/openAIP/openaip-openair-parser/blob/29044bf138a727ddbcb49a55ba6a72891507e420/src/airspace-factory.js#L82 or check every point in an airspace for a given minimum distance. This should be controlled by a new flag, maybe "--check-distance" or something.

What do you think about rhis?

**Comment by reskume** [comment]
Sure, every contribution is great! We are always happy when other people help improve openaip data or related software! Yeah, this issue you are describing is one of the big pain points with openair files. I guess those "errors" are sometimes already part of the AIP that gets published and is used for sourcing as they seemingly don't care about valid geometries when defining those things in spoken word.

To fix this (and many other) issues, the parser has the "fixGeometry" flag which will enable a logic that tries to solve those common geometry issues. There is already a method in place here that removes very near points (duplicates) from the list of polygon points:

https://github.com/openAIP/openaip-openair-parser/blob/29044bf138a727ddbcb49a55ba6a72891507e420/src/airspace.js#LL251C5-L271C6

I think this would be the right place to do this as this will iterate over the complete set of calculated points of the polygon. With this approach, we would also get those parts where self-intersection happens but the points originate from other oddly placed points inside other arc definitions or whatever.

Another approach would be to directly do this in the specific token handler. But this would mean a bigger rewrite since we have to look at the output of the multiple token handler before and after the current one.

Regarding the flag, I would say we can keep the "fixGeometry" and it's not required to introduce a new flag. If it's required for certain use-cases, we could also separate the "fix geometry logic" into several distinct parts that all have their own flag. This way the user has the possibility to define specific methods that are applied to the airspace geometry. But I don't think this is already needed, but I maybe wrong here...

**Comment by bubeck** [comment]
Thanks for the answer. I will take a look at fix geometry and come back
