### ISSUE TITLE
The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### ISSUE THREAD

**Issue by llauner** [openAIP/openaip-openair-parser#33]
With enclosed file (v3) I got the following error:
Error found at line 26402: Geometry of airspace 'ZSM 11 Mt FERRON / Bird Protection Area' starting on line 26402 is invalid. First and last Position are not equivalent.

Then I fix it, but now I'm getting this error:
The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

Any idea ? I'm using of course the same command line:
node cli.js -f /mnt/c/Users/SESA644858/Downloads/france-2023-fixed-v4.txt --validate --debug

[france-2023-fixed-v4.txt](https://github.com/openAIP/openaip-openair-parser/files/11232177/france-2023-fixed-v4.txt)
[france-2023-fixed-v3.txt](https://github.com/openAIP/openaip-openair-parser/files/11232178/france-2023-fixed-v3.txt)

**Comment by reskume** [comment]
Ok, seems you are missing the "output" path. Did you try setting the output file path? This should resolve the error.

**Comment by reskume** [comment]
Currently the output format is hard-coded to GeoJSON. We _could_ implement a debug output in various other formats but since the actual conversion does create Polygon geometries, the actual OpenAIR output would be altered in that way that there are only "DP" definitions and nothing else. All other definitions ("DC", "V X=",...) would be lost.
